# Generated by Django 5.0.1 on 2024-02-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
