# Generated by Django 5.0.1 on 2024-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
