# Generated by Django 5.0.1 on 2024-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
    ]
