# Generated by Django 5.0.1 on 2024-02-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_delete_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='delete_flag',
        ),
    ]
