# Generated by Django 5.0.1 on 2024-02-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_party_remove_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('1', 'Debit'), ('2', 'Credit')], max_length=2)),
                ('amount', models.PositiveIntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.party')),
            ],
        ),
    ]
