# Generated by Django 5.0.1 on 2024-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_client_delete_flag_party_address_party_delete_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
