# Generated by Django 5.0.1 on 2024-02-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_client_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
