# Generated by Django 5.0.1 on 2024-02-08 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_party_name_alter_party_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('user', 'name', 'phone_number')},
        ),
    ]
