# Generated by Django 5.0.1 on 2024-02-14 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_party_user_alter_transaction_form_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.form'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.party'),
        ),
    ]
