# Generated by Django 5.0.2 on 2024-02-17 21:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_party_address_alter_party_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('user', 'name')},
        ),
    ]
