# Generated by Django 5.0.2 on 2024-06-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_manage_transactions', 'Can Manage Transactions'), ('can_manage_sales', 'Can Manage Sales'), ('can_manage_purchase', 'Can Manage Purchase'), ('can_manage_s_p', 'Can Manage Sale/Purchase'), ('can_change_sale', 'Can Change Sale'), ('can_change_purchase', 'Can Change Purchase'), ('can_add_purchase', 'Can Add Purchase'), ('can_add_sale', 'Can Add Sale'))},
        ),
    ]
