# Generated by Django 5.0.2 on 2024-06-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
