# Generated by Django 5.0.2 on 2024-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_conversion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productconversion',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
