# Generated by Django 5.0.2 on 2024-09-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_productconversion_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pallydar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
