# Generated by Django 5.0.2 on 2024-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_transaction_pallydar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
