# Generated by Django 5.0.2 on 2024-09-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_transaction_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=510),
        ),
    ]
